<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="truck_robot">

  <!-- Material definitions for RViz2 -->
  <material name="gray">
    <color rgba="0.5 0.5 0.5 1"/>
  </material>
  
  <material name="blue">
    <color rgba="0.2 0.4 0.8 1"/>
  </material>
  
  <material name="red">
    <color rgba="0.8 0.1 0.1 1"/>
  </material>
  
  <material name="black">
    <color rgba="0.1 0.1 0.1 1"/>
  </material>

  <!-- Define xacro properties for easy customization -->
  <xacro:property name="PI" value="3.14159265359"/>
  
  <!-- Truck dimensions -->
  <xacro:property name="chassis_length" value="1.2"/>
  <xacro:property name="chassis_width" value="0.5"/>
  <xacro:property name="chassis_height" value="0.15"/>
  <xacro:property name="chassis_mass" value="15.0"/>
  
  <xacro:property name="cabin_length" value="0.4"/>
  <xacro:property name="cabin_width" value="0.5"/>
  <xacro:property name="cabin_height" value="0.35"/>
  <xacro:property name="cabin_mass" value="5.0"/>
  
  <!-- Wheel properties -->
  <xacro:property name="wheel_radius" value="0.1"/>
  <xacro:property name="wheel_width" value="0.08"/>
  <xacro:property name="wheel_mass" value="1.0"/>
  <xacro:property name="wheel_offset_x" value="0.35"/>
  <xacro:property name="wheel_offset_y" value="0.3"/>
  <xacro:property name="wheel_offset_z" value="0.0"/>
  
  <!-- LIDAR properties -->
  <xacro:property name="lidar_radius" value="0.05"/>
  <xacro:property name="lidar_height" value="0.07"/>
  <xacro:property name="lidar_mass" value="0.3"/>
  
  <!-- Camera properties -->
  <xacro:property name="camera_size" value="0.05"/>
  <xacro:property name="camera_mass" value="0.1"/>

  <!-- Macro for inertial properties of a box -->
  <xacro:macro name="box_inertia" params="mass length width height">
    <inertial>
      <mass value="${mass}"/>
      <inertia ixx="${(1/12) * mass * (width*width + height*height)}" ixy="0.0" ixz="0.0"
               iyy="${(1/12) * mass * (length*length + height*height)}" iyz="0.0"
               izz="${(1/12) * mass * (length*length + width*width)}"/>
    </inertial>
  </xacro:macro>

  <!-- Macro for inertial properties of a cylinder -->
  <xacro:macro name="cylinder_inertia" params="mass radius height">
    <inertial>
      <mass value="${mass}"/>
      <inertia ixx="${(1/12) * mass * (3*radius*radius + height*height)}" ixy="0.0" ixz="0.0"
               iyy="${(1/12) * mass * (3*radius*radius + height*height)}" iyz="0.0"
               izz="${(1/2) * mass * radius * radius}"/>
    </inertial>
  </xacro:macro>

  <!-- Macro for wheels -->
  <xacro:macro name="wheel" params="prefix reflect_y reflect_x">
    <link name="${prefix}_wheel">
      <visual>
        <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
        <material name="black">
          <color rgba="0.1 0.1 0.1 1"/>
        </material>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
      </collision>
      <xacro:cylinder_inertia mass="${wheel_mass}" radius="${wheel_radius}" height="${wheel_width}"/>
    </link>

    <joint name="${prefix}_wheel_joint" type="continuous">
      <parent link="base_link"/>
      <child link="${prefix}_wheel"/>
      <origin xyz="${reflect_x * wheel_offset_x} ${reflect_y * wheel_offset_y} ${wheel_offset_z}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
    </joint>
  </xacro:macro>

  <!-- Base footprint (for navigation) -->
  <link name="base_footprint"/>

  <!-- Base link (chassis) -->
  <link name="base_link">
    <visual>
      <origin xyz="0 0 ${chassis_height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
      <material name="gray">
        <color rgba="0.5 0.5 0.5 1"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 ${chassis_height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
    </collision>
    <xacro:box_inertia mass="${chassis_mass}" length="${chassis_length}" width="${chassis_width}" height="${chassis_height}"/>
  </link>

  <!-- Joint connecting footprint to base_link -->
  <joint name="base_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link"/>
    <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
  </joint>

  <!-- Cabin link -->
  <link name="cabin_link">
    <visual>
      <origin xyz="0 0 ${cabin_height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${cabin_length} ${cabin_width} ${cabin_height}"/>
      </geometry>
      <material name="blue">
        <color rgba="0.2 0.4 0.8 1"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 ${cabin_height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${cabin_length} ${cabin_width} ${cabin_height}"/>
      </geometry>
    </collision>
    <xacro:box_inertia mass="${cabin_mass}" length="${cabin_length}" width="${cabin_width}" height="${cabin_height}"/>
  </link>

  <!-- Joint connecting cabin to chassis -->
  <joint name="cabin_joint" type="fixed">
    <parent link="base_link"/>
    <child link="cabin_link"/>
    <origin xyz="${chassis_length/2 - cabin_length/2} 0 ${chassis_height}" rpy="0 0 0"/>
  </joint>

  <!-- LIDAR link -->
  <link name="lidar_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${lidar_radius}" length="${lidar_height}"/>
      </geometry>
      <material name="red">
        <color rgba="0.8 0.1 0.1 1"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${lidar_radius}" length="${lidar_height}"/>
      </geometry>
    </collision>
    <xacro:cylinder_inertia mass="${lidar_mass}" radius="${lidar_radius}" height="${lidar_height}"/>
  </link>

  <!-- Joint connecting LIDAR to cabin top -->
  <joint name="lidar_joint" type="fixed">
    <parent link="cabin_link"/>
    <child link="lidar_link"/>
    <origin xyz="0 0 ${cabin_height + lidar_height/2}" rpy="0 0 0"/>
  </joint>

  <!-- Camera link -->
  <link name="camera">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${camera_size} ${camera_size} ${camera_size}"/>
      </geometry>
      <material name="black">
        <color rgba="0.1 0.1 0.1 1"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${camera_size} ${camera_size} ${camera_size}"/>
      </geometry>
    </collision>
    <xacro:box_inertia mass="${camera_mass}" length="${camera_size}" width="${camera_size}" height="${camera_size}"/>
  </link>

  <!-- Joint connecting camera to cabin front -->
  <joint name="camera_joint" type="fixed">
    <parent link="cabin_link"/>
    <child link="camera"/>
    <origin xyz="${cabin_length/2} 0 ${cabin_height/2}" rpy="0 0 0"/>
  </joint>

  <!-- Instantiate wheels -->
  <xacro:wheel prefix="front_left" reflect_y="1" reflect_x="1"/>
  <xacro:wheel prefix="front_right" reflect_y="-1" reflect_x="1"/>
  <xacro:wheel prefix="rear_left" reflect_y="1" reflect_x="-1"/>
  <xacro:wheel prefix="rear_right" reflect_y="-1" reflect_x="-1"/>

  <!-- Gazebo-specific elements (optional but recommended) -->
  <gazebo reference="base_link">
    <material>Gazebo/Grey</material>
  </gazebo>

  <gazebo reference="cabin_link">
    <material>Gazebo/Blue</material>
  </gazebo>

  <gazebo reference="lidar_link">
    <material>Gazebo/Red</material>
    <sensor type="ray" name="lidar_sensor">
      <pose>0 0 0 0 0 0</pose>
      <visualize>true</visualize>
      <update_rate>10</update_rate>
      <ray>
        <scan>
          <horizontal>
            <samples>360</samples>
            <resolution>1</resolution>
            <min_angle>-${PI}</min_angle>
            <max_angle>${PI}</max_angle>
          </horizontal>
        </scan>
        <range>
          <min>0.2</min>
          <max>30.0</max>
          <resolution>0.01</resolution>
        </range>
        <noise>
          <type>gaussian</type>
          <mean>0.0</mean>
          <stddev>0.01</stddev>
        </noise>
      </ray>
      <plugin name="gazebo_ros_lidar" filename="libgazebo_ros_ray_sensor.so">
        <ros>
          <namespace>/truck_robot</namespace>
          <remapping>~/out:=scan</remapping>
        </ros>
        <output_type>sensor_msgs/LaserScan</output_type>
        <frame_name>lidar_link</frame_name>
      </plugin>
    </sensor>
  </gazebo>

  <gazebo>
    <plugin name="gazebo_ros_diff_drive" filename="libgazebo_ros_diff_drive.so">
      <update_rate>50</update_rate>
      <left_joint>front_left_wheel_joint</left_joint>
      <left_joint>rear_left_wheel_joint</left_joint>
      <right_joint>front_right_wheel_joint</right_joint>
      <right_joint>rear_right_wheel_joint</right_joint>
      <wheel_separation>${wheel_offset_y * 2}</wheel_separation>
      <wheel_diameter>${wheel_radius * 2}</wheel_diameter>
      <max_wheel_torque>20</max_wheel_torque>
      <max_wheel_acceleration>1.0</max_wheel_acceleration>
      <command_topic>cmd_vel</command_topic>
      <publish_odom>true</publish_odom>
      <publish_odom_tf>true</publish_odom_tf>
      <publish_wheel_tf>true</publish_wheel_tf>
      <odometry_topic>odom</odometry_topic>
      <odometry_frame>odom</odometry_frame>
      <robot_base_frame>base_footprint</robot_base_frame>
    </plugin>
  </gazebo>

</robot>
